version: '3'
services:
  angular-example:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - '4200:4200'
    volumes:
      - .:/usr/src/app
    restart: always
    environment:
      - ENV=development